import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const facts=JSON.parse(await fs.readFile(path.join(root,'src/facts.json'),'utf8'));
const money=n=>n.toLocaleString('en-US');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const getStarted=`uv tool install 'harbor==0.18.0'\ngit clone https://github.com/GaugeForge/Quantum-Harbor\ncd Quantum-Harbor\ngit checkout ${facts.technical.repoCommit}\nuv sync\ndocker build -t qiqcbench-agent docker/agent/\nuv run python tools/build_qsim_images.py --tasks time_budgeted_hamlearn_10q\nharbor run -p harbor_tasks/time_budgeted_hamlearn_10q -a nop\nharbor view jobs`;
const navItems=[['rules','Rules'],['how-it-works','Challenge Journey'],['getting-started','Build'],['faq','FAQ']];
const email=(subject)=>`mailto:${facts.contact}?subject=${encodeURIComponent(subject)}`;
const arrow='<img class="icon" src="assets/arrow-up-right.svg" alt="">';
const faqs=[
 ['Who can enter?','Individuals and teams of up to three people. There is no academic or professional qualification requirement. Applicable law and valid consent still apply.'],
 ['What exactly am I building?','An agent harness: the code that plans work, invokes tools, manages experiment state and verifies results around a fixed Hunyuan 4 Preview (HY4) model. You may modify an existing harness or build your own.'],
 ['Is registration open?','The registration form is to be announced. Use the participation email link to ask the organizer for information. An email inquiry does not register a team.'],
 ['Are model credits unlimited?','The event model is Tencent Hunyuan 4 Preview (HY4). Exact API quota and development allowance are to be announced. Each team has at most three official full benchmark evaluations.'],
 ['How is the Challenger Award different?','USD 15,000 goes only to the strict first qualifying Hunyuan 4 Preview (HY4) team to exceed the GPT-6 Astra baseline on the hidden leaderboard. If no team exceeds it, the award is not paid. Timestamp, baseline and stacking details will be frozen before registration.'],
 ['Are hidden tasks guaranteed uncontaminated?','No. Public paper tasks and repository material are already accessible. Hidden means withheld during evaluation, not proven absent from training data. Evaluation uses recorded evidence and controlled conditions.'],
 ['Do I need quantum hardware?','No. Quantum-Harbor provides a simulated laboratory. Real-hardware access is not part of the announced competition.'],
 ['What must I open source?','Submitted harness code is required to be AGPL open source. The exact version and release timing will be frozen before registration. Data and trajectory use has separate terms, including named organizer and partner recipients.'],
 ['Where are submissions uploaded?','The event submission interface is not yet released. The public repository supports local task runs. The participant guide labels the proposed competition package separately.']
];
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Build an agent harness around Hunyuan 4 Preview for verified quantum engineering. QIQC Challenge by GaugeForge starts ${facts.schedule.start.label}."><meta name="theme-color" content="#f5f7f8"><title>QIQC Challenge | GaugeForge</title><link rel="stylesheet" href="styles.css"></head><body>
<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="#overview">GaugeForge<span aria-hidden="true">▍</span></a><button id="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Open navigation" title="Open navigation"><img src="assets/menu.svg" alt=""></button><nav id="navigation" aria-label="Main navigation">${navItems.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav></header>
<main id="main">
<section class="hero-stage" id="overview" aria-labelledby="hero-title"><div class="hero">
<div class="hero-field" id="rabi-lab" aria-hidden="true"><img class="field-fallback" src="assets/rabi-calibration.webp" alt=""><canvas id="rabi-canvas"></canvas></div>
<div class="field-caption protected" id="rabi-caption"><p>RABI OSCILLATIONS</p><span>Pulse duration × detuning · ideal two-level model</span><div><span>Illustration, not experimental data</span><button id="rabi-play" type="button" aria-label="Pause background animation">Ⅱ &nbsp; Pause motion</button></div></div>
<div class="hero-inner wrap">
<div class="hero-copy">
<h1 id="hero-title" class="protected"><span class="title-line"><span class="motion-surface">Agentic Quantum</span></span><br><span class="title-line"><span class="motion-surface"><em>Coding Challenge</em></span></span></h1>
<p class="event-intro protected"><span class="intro-line">An online challenge to build AI agents for quantum engineering.</span><span class="intro-line">Design your harness around Hunyuan 4 Preview and put it to the test.</span></p>
<p class="hero-slogan protected"><mark>${facts.messaging.hook}</mark></p>
</div>
<section class="entry-basics" aria-label="Participation essentials">
<div id="timeline" class="entry-timeline"><span class="basic-label">WHEN <small>2026 · UTC+8</small></span><ol>${[['start','Competition begins'],['deadline','Submission deadline'],['demo','Demo Day']].map(([key,label])=>`<li><span class="timeline-event">${label}</span><time datetime="${facts.schedule[key].date}">NOV ${facts.schedule[key].date.slice(-2)}</time></li>`).join('')}</ol></div>
<div class="entry-details"><div class="entry-who"><span class="basic-label">WHO CAN JOIN</span><h3>Everyone. Solo or a team.</h3><p>${facts.rules.teamMin}–${facts.rules.teamMax} people per team. No academic or professional qualification required.</p></div><div class="entry-how"><span class="basic-label">HOW TO JOIN</span><h3>Form a team. Build your harness.</h3><p>Register, practice in the public lab, then submit your harness for evaluation.</p></div><div class="entry-register">${facts.links.registration?`<a class="button primary register-now" href="${facts.links.registration}">Register now ${arrow}</a>`:`<button class="button primary register-now" id="register-now" type="button" aria-haspopup="dialog">Register now ${arrow}</button>`}<span>${facts.links.registration?'Join the challenge.':'Registration form coming soon.'}</span></div></div>
<div class="prize-overview"><article><span class="rule-label">PLACEMENT PRIZE POOL</span><h3 aria-label="USD ${money(facts.prizes.placesTotal)}"><span aria-hidden="true">USD <span class="prize-number" data-amount="${facts.prizes.placesTotal}" style="--number-width:${money(facts.prizes.placesTotal).length}ch">${money(facts.prizes.placesTotal)}</span></span></h3><p>Total across the five placement awards.</p><div class="place-amounts">${facts.prizes.places.map((v,i)=>`<span><small>#${i+1}</small> $${money(v)}</span>`).join('')}</div></article><article class="challenger-prize"><span class="rule-label">THE CHALLENGER AWARD</span><h3 aria-label="USD ${money(facts.prizes.challengerAmount)}"><span aria-hidden="true">USD <span class="prize-number" data-amount="${facts.prizes.challengerAmount}" style="--number-width:${money(facts.prizes.challengerAmount).length}ch">${money(facts.prizes.challengerAmount)}</span></span></h3><p>Only the <strong>strict first team</strong> to exceed GPT-6 Astra on the hidden leaderboard. If nobody exceeds it, the award is not paid.</p></article></div>
</section>
</div>
</div></section>
<section class="section rules-section" id="rules" aria-labelledby="rules-title"><div class="wrap">
<div class="section-heading heading-split"><div><p class="eyebrow">01 / THE RULES</p><h2 id="rules-title">One model. Your engineering.</h2></div><a class="text-link" href="downloads/participant-guide.html">Participant guide ${arrow}</a></div>
<div class="rules-layout"><div class="rule-facts">
<article class="rule-row"><span class="rule-number">01</span><div><span class="rule-label">THE MODEL</span><h3>Tencent Hunyuan 4 Preview <small>(HY4)</small></h3><p>The same foundation model for every team.</p></div></article>
<article class="rule-row"><span class="rule-number">02</span><div><span class="rule-label">THE BENCHMARK</span><h3>${facts.rules.eventTaskCount} QIQCBench tasks</h3><p>${facts.rules.publicTasks} public tasks to explore. ${facts.rules.eventTaskCount-facts.rules.publicTasks} hidden tasks for evaluation.</p></div></article>
<article class="rule-row"><span class="rule-number">03</span><div><span class="rule-label">THE LIMIT</span><h3>Up to ${facts.rules.maxFullEvaluations} full evaluations</h3><p>Per team, across the complete ${facts.rules.eventTaskCount}-task benchmark.</p></div></article>
<article class="rule-row"><span class="rule-number">04</span><div><span class="rule-label">THE CODE</span><h3>AGPL open-source harness</h3><p>Submit the orchestration you build around the model.</p></div></article>
</div>
<div class="evaluation-demo" data-stage="0">
<div class="eval-header"><div><span class="eval-eyebrow">FOLLOW ONE TEAM · INTERACTIVE EXAMPLE</span><h3>What happens in one evaluation?</h3></div><div class="eval-header-actions"><button id="demo-reset" type="button" class="reset">Reset</button><button id="demo-next" type="button" class="button step-button">Next step →</button></div></div>
<div class="eval-path"><span class="eval-path-progress"></span><div class="eval-station" data-station="0"><i>1</i><span>Your harness<small>Fixed HY4 model · AGPL code</small></span></div><div class="eval-station" data-station="1"><i>2</i><span>All 49 tasks<small>5 public + 44 hidden</small></span></div><div class="eval-station" data-station="2"><i>3</i><span>Check the evidence<small>Inspect the execution record</small></span></div><div class="eval-station" data-station="3"><i>4</i><span>One attempt used<small>Up to 3 per team</small></span></div></div>
<div class="eval-walkthrough">
<div class="eval-visual" aria-hidden="true">

<div class="eval-scene"><div class="eval-scene-panel" data-scene="0"><span class="scene-kicker">YOUR CODE + THE FIXED MODEL</span><div class="harness-pair"><b>Harness</b><span>+</span><b>HY4</b></div><p>You design the decisions and tool use.</p></div><div class="eval-scene-panel" data-scene="1" hidden><span class="scene-kicker">ONE SHARED BENCHMARK</span><div class="task-pair"><div><strong>5</strong><span>Public</span></div><b>+</b><div><strong>44</strong><span>Hidden</span></div><b>=</b><div><strong>49</strong><span>Tasks</span></div></div><p>Both groups belong to the same full evaluation.</p></div><div class="eval-scene-panel" data-scene="2" hidden><span class="scene-kicker">A RESULT NEEDS EVIDENCE</span><div class="evidence-chain"><span>Tool calls</span><i>→</i><span>Readouts</span><i>→</i><span>Checks</span></div><p>Inspect what the agent actually did.</p></div><div class="eval-scene-panel" data-scene="3" hidden><span class="scene-kicker">FULL EVALUATION COMPLETE</span><strong id="scene-attempt">1 of 3 attempts used</strong><p>No example scores are invented or revealed.</p></div></div>
</div>
<div class="eval-explanation" aria-live="polite" aria-atomic="true"><span id="eval-step-label" class="rule-label">BEFORE YOU START</span><h4 id="eval-step-title">Follow a complete run.</h4><p id="eval-step-copy">This is a visual explanation of the competition rules. Nothing is submitted, no model is called, and your real evaluation allowance is unaffected.</p><div class="eval-takeaway"><span>THE KEY IDEA</span><p id="eval-step-takeaway">One full evaluation covers all 49 tasks. It is one attempt, not 49 attempts.</p></div></div>
</div>
<div class="eval-quota"><span>Example attempts</span><div class="attempts"><span>1</span><span>2</span><span>3</span></div><strong id="attempt-count">0 / 3 used</strong></div>
<p id="evaluation-result" class="demo-result" role="status">Click Next step to follow the process. No real evaluation runs here.</p>
</div>
</div>

<div class="award-demo"><div><span class="rule-label">WHAT COUNTS AS A BREAKTHROUGH?</span><h3>Exceed it. Be first.</h3><p>Choose a scenario to see how the challenger rule applies.</p></div><div class="award-example"><div class="scenario-buttons" role="group" aria-label="Challenger award examples"><button type="button" data-scenario="first" aria-pressed="true">First to exceed</button><button type="button" data-scenario="tie" aria-pressed="false">Equal to baseline</button><button type="button" data-scenario="later" aria-pressed="false">Later to exceed</button><button type="button" data-scenario="none" aria-pressed="false">Nobody exceeds</button></div><div id="award-result" role="status"><strong>One qualifying team. USD 15,000.</strong><p>The first qualifying team whose hidden score is strictly above the frozen GPT-6 Astra baseline receives the challenger award.</p></div><small>Illustrative scenarios, not actual scores. Baseline, timestamp procedure, prize stacking and payment terms are still to be confirmed.</small></div></div>
</div></section>
<section class="section flow-section" id="how-it-works"><div class="wrap"><div class="section-heading heading-split"><div><p class="eyebrow">02 / THE JOURNEY</p><h2>From an idea<br>to a verified result.</h2></div><p>Follow a sample team's path.<br>Click each step to see what happens.</p></div><div class="flow-tabs" role="group" aria-label="Competition walkthrough">${['Build','Practice','Evaluate','Demo Day'].map((name,i)=>`<button type="button" data-step="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${name}<span aria-hidden="true">↗</span></button>`).join('')}</div><div class="flow-demo"><div class="flow-illustration" aria-hidden="true"><span id="flow-diagram-label">YOUR HARNESS</span><div class="flow-nodes"><span id="flow-node-a">Plan</span><i>→</i><span id="flow-node-b">Use tools</span><i>→</i><span id="flow-node-c">Verify</span></div><div class="flow-loop">↳ &nbsp; Learn from the evidence. Try again.</div></div><div class="flow-explanation" role="status"><span class="rule-label" id="flow-date">BEFORE THE COMPETITION</span><h3 id="flow-title">Build the decision-making around HY4.</h3><p id="flow-copy">A sample team writes a harness that chooses a quantum experiment, calls the lab tools, reads the result and decides what to do next. The model stays fixed; the orchestration is theirs.</p><span class="flow-note" id="flow-note">Illustrative workflow · no model call or experiment is running here.</span></div></div><div class="research-line"><p>Built on <strong>QIQCBench + Quantum-Harbor</strong>.</p><a href="${facts.links.paper}">Read the paper ${arrow}</a><a href="${facts.links.benchmark}">Explore the benchmark ${arrow}</a></div></div></section>
<section class="section wrap" id="getting-started"><div class="section-heading"><p class="eyebrow">04 / GETTING STARTED</p><h2>Run the public lab.</h2><p>Docker, uv, git and Python 3.11+. On Windows, use Linux containers through WSL2. The no-key check below tests the public environment.</p></div><div class="terminal"><div class="terminal-bar"><span>Quantum-Harbor / Harbor 0.18.0</span><button id="copy-code" title="Copy installation commands" aria-label="Copy installation commands"><img src="assets/copy.svg" alt=""></button></div><pre><code id="install-code">${esc(getStarted)}</code></pre></div><p id="copy-status" role="status" class="small"></p><p class="note"><strong>Expected result: reward 0.</strong> The <code>nop</code> agent performs no science. This is an installation check, not an official entry.</p><p>The public repository includes example agent configurations. The competition Hunyuan 4 Preview adapter, exact model ID and upload service are to be announced. The current examples must not be presented as a working event integration.</p><div class="actions"><a class="button secondary" href="${facts.links.repository}">Open Quantum-Harbor ${arrow}</a><a class="text-link" href="${facts.links.repository}/blob/${facts.technical.repoCommit}/docs/getting-started/installation.md">Installation reference ${arrow}</a></div></section>
<section class="section partners-section" id="partners"><div class="wrap"><p class="eyebrow">05 / PARTNERS</p><h2>Bring your community or expertise.</h2><div class="partner-content"><p>Hosted by <strong>GaugeForge</strong>. Community distribution, expert review, model support and post-event experiments are available ways to contribute.</p><p>External partners will be announced after confirmation. No external organization is currently listed as a confirmed event partner.</p></div><div class="actions"><a class="button primary" href="${email('QIQC Challenge partnership inquiry')}">Discuss a partnership ${arrow}</a><a class="text-link" href="downloads/partner-handbook.pdf">Partner handbook PDF <img class="icon" src="assets/download.svg" alt=""></a></div></div></section>
<section class="section wrap" id="faq"><div class="section-heading"><p class="eyebrow">06 / FAQ</p><h2>Before you enter.</h2></div><div class="faq">${faqs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>
<section class="participate-band"><div class="wrap"><p class="eyebrow">BUILD SOMETHING VERIFIABLE</p><h2>Join the QIQC Challenge.</h2><p>Starts ${facts.schedule.start.label}. Final submission: ${facts.schedule.deadline.label}. Demo Day: ${facts.schedule.demo.label}. Registration link: To be announced.</p><a class="button primary" href="${email('QIQC Challenge participation inquiry')}">Contact to participate ${arrow}</a><a class="contact" href="mailto:${facts.contact}">${facts.contact}</a><p class="small">Email inquiry only. Your mail application opens; nothing is sent automatically.</p></div></section></main>
${facts.links.registration?'':`<dialog id="registration-dialog" aria-labelledby="registration-title" aria-describedby="registration-description"><button type="button" class="dialog-close" aria-label="Close registration information">×</button><p class="eyebrow">QIQC CHALLENGE / REGISTRATION</p><h2 id="registration-title">Join the challenge.</h2><p id="registration-description">The official registration form is coming soon. Contact GaugeForge for participation information in the meantime.</p><a class="button primary" href="${email('QIQC Challenge registration inquiry')}">Contact the organizer ${arrow}</a><p class="dialog-note">An email inquiry does not register a team. Nothing is submitted automatically.</p></dialog>`}
<footer class="site-footer wrap"><a class="brand" href="#overview">GaugeForge<span aria-hidden="true">▍</span></a><p>QIQC Challenge / ${facts.version}</p><p>No registration data is collected on this site. Inquiries are handled by GaugeForge.<br>Data rights and the final participant privacy notice will be available before registration.</p><a href="downloads/participant-guide.html">Privacy and participant terms</a></footer><script src="app.js" defer></script></body></html>`;
await fs.writeFile(path.join(root,'src/index.html'),html);
await fs.writeFile(path.join(root,'src/404.html'),'<!doctype html><html lang="en"><meta charset="utf-8"><title>Page not found | QIQC</title><h1>Page not found</h1><a href="/">Return to QIQC Challenge</a></html>');
await fs.writeFile(path.join(root,'src/_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Content-Security-Policy: default-src \'self\'; img-src \'self\' data:; style-src \'self\' \'unsafe-inline\'; script-src \'self\'; object-src \'none\'; base-uri \'self\'; form-action \'none\'\n');
